
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA CONSOLE DIVIDE DOT EQ FOR GE GLOBAL GT ID INT LBRACE LE LOG LPAREN LT MINUS NE NUMBER OUT PLUS PRINTLN RBRACE RPAREN SEMICOLON SINGLE_QUOTE STRING SYSTEM TIMES VARprogram : declaration for_loopdeclaration : INT ID SEMICOLONfor_loop : FOR LPAREN assignment SEMICOLON condition SEMICOLON increment RPAREN LBRACE block RBRACEassignment : ID ASSIGN NUMBERcondition : ID LE NUMBERincrement : ID PLUS PLUSblock : system_println_statementsystem_println_statement : SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON'
    
_lr_action_items = {'INT':([0,],[3,]),'$end':([1,4,28,],[0,-1,-3,]),'FOR':([2,8,],[5,-2,]),'ID':([3,7,11,16,33,],[6,10,14,19,34,]),'LPAREN':([5,32,],[7,33,]),'SEMICOLON':([6,9,13,15,20,35,],[8,11,16,-4,-5,36,]),'ASSIGN':([10,],[12,]),'NUMBER':([12,17,],[15,20,]),'LE':([14,],[17,]),'RPAREN':([18,24,34,],[21,-6,35,]),'PLUS':([19,22,],[22,24,]),'LBRACE':([21,],[23,]),'SYSTEM':([23,],[27,]),'RBRACE':([25,26,36,],[28,-7,-8,]),'DOT':([27,30,],[29,31,]),'OUT':([29,],[30,]),'PRINTLN':([31,],[32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declaration':([0,],[2,]),'for_loop':([2,],[4,]),'assignment':([7,],[9,]),'condition':([11,],[13,]),'increment':([16,],[18,]),'block':([23,],[25,]),'system_println_statement':([23,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declaration for_loop','program',2,'p_program','parser_1.py',9),
  ('declaration -> INT ID SEMICOLON','declaration',3,'p_declaration','parser_1.py',15),
  ('for_loop -> FOR LPAREN assignment SEMICOLON condition SEMICOLON increment RPAREN LBRACE block RBRACE','for_loop',11,'p_for_loop','parser_1.py',20),
  ('assignment -> ID ASSIGN NUMBER','assignment',3,'p_assignment','parser_1.py',25),
  ('condition -> ID LE NUMBER','condition',3,'p_condition','parser_1.py',30),
  ('increment -> ID PLUS PLUS','increment',3,'p_increment','parser_1.py',35),
  ('block -> system_println_statement','block',1,'p_block','parser_1.py',40),
  ('system_println_statement -> SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON','system_println_statement',9,'p_system_println_statement','parser_1.py',44),
]
